### ISSUE TITLE
Pár drobných issues

### ISSUE THREAD

**Issue by frenzymadness** [pyvec/bookshelf#29]
Nas stránkce [jak to funguje](https://books.pyvo.cz/info/):
* [x] URL adresa Pyva by měla být odkazem
* [x] zmínka `@encukou` by také mohla být odkazem na jeho twitter nebo github (dle preference)
* [x] `encukou@gmail.com` by také mohl být odkaz s `mailto:`

Na githubu:
* [x] projekt by mohl obsahovat šablonu pro issues, aby knihychtivý člověk na nic nezapoměl při jeho tvorbě - [jak na to](https://github.blog/2016-02-17-issue-and-pull-request-templates/)

**Comment by frenzymadness** [comment]
Poslední bod prosím ignorovat. Vídím, že se issue předvyplní pro konkrétní knihu.

**Comment by encukou** [comment]
Díky za připomínky!
https://github.com/pyvec/bookshelf/pull/31
