### ISSUE TITLE
Chci si půjčit knížku Ponořme se do Python(u) 3

### ISSUE THREAD

**Issue by Techn1k9** [pyvec/bookshelf#35]
Chci si půjčit knížku [Ponořme se do Python(u) 3].

Chci si ji převezít na Pyvu v ____.

(cc @encukou, @hroncok, Katka L, PL Brno)

[Ponořme se do Python(u) 3]: https://books.pyvo.cz/ponormese/

**Comment by hroncok** [comment]
Ahoj. V jakém městě?

**Comment by encukou** [comment]
Bez informace o místě se knížka nedá půjčit.
