### ISSUE TITLE
Chci si půjčit knížku Flask Web Development

### ISSUE THREAD

**Issue by Simecekk** [pyvec/bookshelf#36]
Chci si půjčit knížku [Flask Web Development].

Chci si ji převezít na Pyvu v ____.

(cc @encukou)

[Flask Web Development]: https://books.pyvo.cz/flask-web-dev/

**Comment by encukou** [comment]
Na kterém Pyvu?

**Comment by Simecekk** [comment]
Ahoj Petře,

až teď jsem si všiml, že pyvo v HK již bylo 11.4.

Kouknu se po knížce jinde, ale i tak děkuji za ochotu.

David



Odesláno z aplikace Pošta pro Windows 10

Od: Petr Viktorin
Odesláno:úterý 23. dubna 2019 16:37
Komu: pyvec/bookshelf
Kopie: Simecekk; Author
Předmět: Re: [pyvec/bookshelf] Chci si půjčit knížku Flask Web Development (#36)

Na kterém Pyvu?

**Comment by encukou** [comment]
Možná bude další. Kdyžtak to tu otevři znovu.
