### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by TomasRoj** [pyvec/bookshelf#38]
Ahoj,

v jaké licenci je tento projekt? Tento nápad se mi líbí a proto bych tohoto principu využil ve svém, větším projektu. Nechtěl bych tedy Váš projekt/nápad/kód okopírovat. BTW > kdyby mi někdo chtěl s tímto projektem pomoc, budu rád!

**Comment by hroncok** [comment]
Ta tady evidentně chybí.

**Comment by TomasRoj** [comment]
Vidím no 👍

**Comment by encukou** [comment]
MIT licence přidána v #39

**Comment by TomasRoj** [comment]
Díky, můžu se teď orientovat podle ní.
