### ISSUE TITLE
Chci si půjčit knížku Hackers and Painters: Big Ideas from the Computer Age

### ISSUE THREAD

**Issue by Tricerator** [pyvec/bookshelf#41]
Chci si půjčit knížku [Hackers and Painters: Big Ideas from the Computer Age].

Chci si ji převezít na Pyvu v ____.

(cc @encukou)

[Hackers and Painters: Big Ideas from the Computer Age]: https://books.pyvo.cz/hackers_painters/

**Comment by encukou** [comment]
Na kterém že Pyvu?

**Comment by encukou** [comment]
Na které Pyvo jii mám donést?
