### ISSUE TITLE
Chci si půjčit knížku Clean Code

### ISSUE THREAD

**Issue by Tricerator** [pyvec/bookshelf#42]
Chci si půjčit knížku [Clean Code].

Chci si ji převezít na Pyvu v ____.

(cc @JirkaV)

[Clean Code]: https://books.pyvo.cz/cleancode/

**Comment by encukou** [comment]
Na kterém že Pyvu?

**Comment by Tricerator** [comment]
Nečekal jsem tak rychlou odezvu. Koukal jsem se na Pyva a do srpna se nemohu zůčastnit. Bylo by možné opět forknout, až budou známá data dalších "Pyv"?

**Comment by JirkaV** [comment]
Spis mi napis (do mailu) adresu, knizku it poslu. Na Prazskem PyVu jsem uz nebyl cca rok.
