### ISSUE TITLE
Chci si půjčit knížky Python Tricks: The Book a The Internet of Risky Things

### ISSUE THREAD

**Issue by befeleme** [pyvec/bookshelf#48]
Chci si půjčit knížku [Python Tricks: The Book].

Chci si ji převezít 17. 9 na srazu v Kinali (resp. na Pyvu v Brně).

(cc @encukou)

[Python Tricks: The Book]: https://books.pyvo.cz/python-tricks/

**Comment by encukou** [comment]
Dal jsem je k projektoru, tak je snad nezapomenu :)

**Comment by encukou** [comment]
Vyřešeno v https://github.com/pyvec/bookshelf/commit/8613e6c98b403361ac21cf23d5c5bae07cb47ed9 :)
