### ISSUE TITLE
Chci si půjčit knížku The Internet of Risky Things

### ISSUE THREAD

**Issue by befeleme** [pyvec/bookshelf#49]
Chci si půjčit knížku [The Internet of Risky Things].

Chci si ji převezít na Pyvu v Brně, nebo 17. 9 v Kinali spolu s #48.

(cc @encukou)

[The Internet of Risky Things]: https://books.pyvo.cz/risky-iot/

**Comment by encukou** [comment]
Spojím to s #48.
