### ISSUE TITLE
Chci si půjčit knížku Ponořme se do Python(u) 3

### ISSUE THREAD

**Issue by olikrajcovic** [pyvec/bookshelf#51]
Chci si půjčit knížku [Ponořme se do Python(u) 3].

Chci si ji převezít na Pyvu v ____.

(cc @encukou, @hroncok)

[Ponořme se do Python(u) 3]: https://books.pyvo.cz/ponormese/

**Comment by hroncok** [comment]
> Chci si ji převezít na Pyvu v ____.

Na Pyvu kde?
