### ISSUE TITLE
Chci si půjčit knížku Cython - A guide for Python programmers

### ISSUE THREAD

**Issue by IJordieI** [pyvec/bookshelf#52]
#Chci si půjčit knížku [Cython - A guide for Python programmers].

Chci si ji převezít na Pyvu v ____.

(cc @tjanovsky)

[Cython - A guide for Python programmers]: https://books.pyvo.cz/cython/

**Comment by encukou** [comment]
Ještě prosím napiš, kde si ji chceš převzít. Města kde se konají srazy najdeš na https://pyvo.cz/
