### ISSUE TITLE
Chci si půjčit knížku Hacking Secret Ciphers with Python

### ISSUE THREAD

**Issue by mportesdev** [pyvec/bookshelf#60]
Chci si půjčit knížku [Hacking Secret Ciphers with Python].

Chci si ji převzít na Pyvu v Praze 15. 1.

(cc @JirkaV)

[Hacking Secret Ciphers with Python]: https://books.pyvo.cz/hackingsecretciphers/

**Comment by JirkaV** [comment]
Omlouvam se, ale tu knizku uz nemam. Musim ji uz konecne smazat z nabidky :(

Uprimne, nebyla nic moc, proto jsem se ji zbavil.

**Comment by mportesdev** [comment]
Dobře, díky za info.
