### ISSUE TITLE
Chci si půjčit knížku Python Tricks: The Book

### ISSUE THREAD

**Issue by mportesdev** [pyvec/bookshelf#66]
Ahoj,
chci si půjčit (resp. stáhnout zpět k sobě) knížku [Python Tricks: The Book].

Chci si ji převzít buď na Pyvu v Praze 19. 8. 2020, anebo (radši) kdykoliv jindy někde v Praze, jelikož se středami večer jsem na tom všeobecně trochu blbě.

Zároveň bych se u knížky chtěl zapsat jako `keeper` a nechat si ji u sebe, pokud samozřejmě nebude zájemce o půjčení. Pošlu PR.

(cc @encukou)

[Python Tricks: The Book]: https://books.pyvo.cz/python-tricks/

**Comment by encukou** [comment]
Dal jsem si ji do batohu, takže do Prahy ji přivezu :)
Víš o někom, kdo může přijít na Pyvo a převzít ji? Já do Prahy bohužel jezdím jen v ty středy.

**Comment by mportesdev** [comment]
Ahoj, díky.

Kdyby to bylo zase u té Letné/Stromovky, tak se tam minimálně na otočku
zastavit zvládnu. Ten Věneček už by byl trochu horší. Nevíš, kde se to
plánuje?

Michal

**Comment by encukou** [comment]
Pokud vím tak Věneček je stále zavřený, takže to bude jinde. Nevím ještě kde.

Jinak v tu středu přes den budu nejspíš okolo Vltavské.

**Comment by encukou** [comment]
Viz https://github.com/pyvec/bookshelf/pull/67
