### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by encukou** [pyvec/bookshelf#7]
Knížek už je tu spousta, chtělo by to nějaké přehlednější rozhraní.

**Comment by honzajavorek** [comment]
Možná nějaká tabulka?

``` markdown
| Docker tool      | Version                 |
|:-----------------|:------------------------|
| `docker`         | 1.7.0 (build 0baf609)   |
| `docker-compose` | 1.3.0                   |
```

<img width="413" alt="screen shot 2015-07-28 at 21 04 44" src="https://cloud.githubusercontent.com/assets/283441/8940830/4307b252-356c-11e5-883b-6fdcb81036c2.png">

**Comment by encukou** [comment]
@starenka prý chce udělat appku :)

**Comment by honzajavorek** [comment]
@starenka @encukou Nějakej pokrok? Napadlo mě, že by to klidně mohlo být součástí https://github.com/pyvec/python.cz/ prostě jako stránka. Nebo https://github.com/pyvec/pyvo.cz/ Ale může být zvlášť, nemám nic proti. Když to bude OSS, můžou to využít i jiný srazy.

**Comment by starenka** [comment]
Vubec sem se k tomu nedostal, cece :(

**Comment by hroncok** [comment]
@encukou Semestrálka na MI-PYT?

**Comment by encukou** [comment]
To nevím, přijde mi že je to spíš na UX než programování.

**Comment by encukou** [comment]
Je to na https://books.pyvo.cz/. Díky, @vahalova :)

**Comment by honzajavorek** [comment]
@encukou Nechces hodit nakej hezkej announcement na Pyonyry, Twitter, Slack? Je to fakt povedeny!

**Comment by encukou** [comment]
@honzajavorek Já jsem zapšklý asociál a nerad dávám odkazy na místa které pak nesleduju.
Nechceš se toho ujmout ty? Nebo @vahalova? :)

**Comment by encukou** [comment]
Na Slack jsem to dal :)
