### ISSUE TITLE
Chci si půjčit knížku Effective PyCharm

### ISSUE THREAD

**Issue by Falkomotion** [pyvec/bookshelf#72]
Chci si půjčit knížku [Effective PyCharm].

Chci si ji převzít na Pyvu v ____. <- sem dopiš město a datum. 
Přehled Pyv najdeš na https://pyvo.cz/

(cc @encukou, @myrmica-habilis)

[Effective PyCharm]: https://books.pyvo.cz/effective-pycharm/

**Comment by encukou** [comment]
A kam ji teda mám přinést? :)

**Comment by Falkomotion** [comment]
Zdravim.

Uz som si vsetko zohnal, ale diky moc.

Dne st 21. 4. 2021 11:57 uživatel Petr Viktorin ***@***.***>
napsal:
