### ISSUE TITLE
Chci si půjčit knížku Python pro hackery a reverzní inženýrství

### ISSUE THREAD

**Issue by MichalVilimek** [pyvec/bookshelf#75]
Chci si půjčit knížku [Python pro hackery a reverzní inženýrství].

Bylo by možné knihu k zápůjčení zaslat například do Zásilkovny?
Děkuji Michal

(cc @encukou)

[Python pro hackery a reverzní inženýrství]: https://books.pyvo.cz/pro-hackery/

**Comment by encukou** [comment]
Během Covidu jsem trochu přemýšlel jak to s knihovničkou udělat když lidi nebudou chodit na srazy. Posílat je poštou/zásilkovnou lidem které jsem nikdy nepotkal js přece jen trochu jiné než jak jsem si knihovničku původně představoval.
Napadlo mě, když už se musí operovat s platbou za Zásilkovnu, to vyřešit vratnou zálohou -- dejme tomu 500,-, po vrácení vrátím. Dávalo by to tak smysl?

**Comment by MichalVilimek** [comment]
Zdravím jj klidně jsem pro zálohu za půjčení.Jak by jsme to tedy mohli provést ?Zaslal bych Vám zálohu na účet?

**Comment by encukou** [comment]
OK! Domluvíme se mailem, pobočku Zásilkovny a číslo účtu už memusíme řešit transparentně tady :)

**Comment by MichalVilimek** [comment]
OK.Díky

**Comment by encukou** [comment]
Knížka je na cestě.
Zásilkovna potřebuje pro doručení jméno, e-mail a telefon, tyhle osobní informace jsem jim poskytnul. A poslal jsem svoje info na vrácení.

A zjistil lsem že na první zásilku z nového účtu má Zásilkovna akci, odeslání bylo za korunu. Až knížka přijde zpátky, vrátím zálohu i se zásilkovným :)

**Comment by encukou** [comment]
Kniha se vrátila, zálohu jsem poslal zpátky :)

**Comment by MichalVilimek** [comment]
Dobrý den,moc děkuji za půjčení :-)

Dne 2022-06-23 13:21, Petr Viktorin napsal:
