### ISSUE TITLE
AttributeError: module 'jinja2' has no attribute 'Markup'

### ISSUE THREAD

**Issue by mportesdev** [pyvec/bookshelf#79]
Při lokálním servírování adresa `http://127.0.0.1:8003/info/` hází chybu `AttributeError: module 'jinja2' has no attribute 'Markup'`

**Comment by encukou** [comment]
Jo, ten kód pár let nikdo nepustil, tak nefunguje s aktuální Jinjou :(
Workaround je `pip install 'jinja2<3.0'`

**Comment by mportesdev** [comment]
Podle dokumentace se má použít [markupsafe.Markup](https://markupsafe.palletsprojects.com/en/2.1.x/escaping/#markupsafe.Markup)

**Comment by mportesdev** [comment]
S `markupsafe.Markup` to zdá se funguje, vytvořil jsem #80
